# Generated by Django 4.2.10 on 2024-02-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_group_user_group_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='user',
        ),
    ]
