# Generated by Django 4.2.10 on 2024-02-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_users_group_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='users',
        ),
    ]
