# Generated by Django 4.2.10 on 2024-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_group_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_users_per_group',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
